logo: Bizness Analytics Blog # add logo name
title: Bizness Analytics Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Welcome to era of Analytics
banner-desc: # add banner description

# Author settings
author-pic: Logo.jpg # your photo
author-name: Bizness Analytics # your name
about-author: Bizness Analytics is an enterprise data and analytics solution provider. Our clients hire us to acquire, enrich and measure their data so they can make smarter, better decisions about their business. # about author
email: client.service@biznessanalytics.com # your email
phone: +971 (50) 553 3140  # your pnone number
website: https://biznesaanalytics.com # you website

# Social link
google_url:    http://www.biznessanalytics.com/ # add url link
twitter_url:   https://twitter.com/BiznessAnalytix # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  https://www.facebook.com/bizness.analytics # add url link
linkedin_url: https://www.linkedin.com/company/biznessanalytics/ # add url link 

# Disqus
discus_identifier: biznessanalytics # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
